[package]
name = "контаминация"
version = "0.1.0"
authors = ["Leon Minasyan <ierehon1905@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
